const DEVICE_TYPES = {
  CHROMECAST: 'DEVICE_TYPE_CHROMECAST',
  EWELINK: 'DEVICE_TYPE_EWELINK'
}

const DEVICE_STATUS = {
  UNKNOWN: 'UNKNOWN',
  READY: 'READY'
}

module.exports = {
  DEVICE_TYPES,
  DEVICE_STATUS
}
